### PR TITLE
3-letterrackjava creation 

### LINKED ISSUE #3: LetterRack.java Creation
Create the LetterRack.java class based on this CRC Card:
image

### PR DESCRIPTION
**Pull request by JosephSun2003**
Finished the creation of Letter Rack.

closes #3

### CODE REVIEW

**Review by minaccchiang — COMMENTED** [review]
For the removeLetters, what if the error occurs? 
findTile will return -1 if it cannot find the letter and it will be sent to removeLetters and it will become this.LETTERS[-1] = null. I thought this is invalid.

**Comment by JosephSun2003** [comment]
> For the removeLetters, what if the error occurs? findTile will return -1 if it cannot find the letter and it will be sent to removeLetters and it will become this.LETTERS[-1] = null. I thought this is invalid.

I'm thinking as long as we keep the inputs within the specified parameters, it should be fine as this is supposed to be mostly untouched from inputs. If it was closer to the input, I would be more defensive (check inputs) but I figured as long as we follow input parameters and do the checking in the controller or user story, it should be fine. 

That said, I might make the method throw an exception if, on the off chance, it does get a bad input.

**Review by minaccchiang — APPROVED** [review]

**Review by patelhrid — APPROVED** [review]
looks like it works

**Review by patelhrid — APPROVED** [review]

**Review by JosephUofT — APPROVED** [review]
good job

**Review by minaccchiang — APPROVED** [review]
Great

**Pull request merged**
