### PR TITLE
Controller presenter creation

### LINKED ISSUE #6: Presenter.java and Controller.java Creation
Create Presenter and Controller

Screen Shot 2022-10-24 at 11 07 55 AM

Screen Shot 2022-10-24 at 11 06 53 AM

Additional Notes:
- This will be done last for a few reasons:

1.  This will be heavily dependent on higher level components, mostly on the user stories
2.  If created without the user stories, it will become harder to debug due to a large number of errors regarding missing methods, attributes, etc. which will be hard to differientate from coding problems and makes it more difficult to test.

### PR DESCRIPTION
**Pull request by JosephSun2003**
Closes #6
Adds the initial version of the controller, presenter and viewModel.

### CODE REVIEW

**Review by ethanhonest — DISMISSED** [review]
LGTM!

**Review by minaccchiang — APPROVED** [review]

**Review by minaccchiang — APPROVED** [review]

**Review by patelhrid — APPROVED** [review]
noice

**Review by ethanhonest — APPROVED** [review]
LGTM!

**Review by djesurumc — APPROVED** [review]
Looks good. The Presenter and Controller are essential parts of our program. Need these to finish the main. Kind of skeptical about the changes to the gradle.build though

**Pull request merged**
