### PR TITLE
Added presenter interaction to save and reload use cases

### PR DESCRIPTION
**Pull request by djesurumc**
Added response model and output boundaries for save game use case and reload game use case 
Fixed my tests to reflect these changes
Implemented Outputboundary for both use cases to Presenter and added relevant method

### CODE REVIEW

**Review by ethanhonest — APPROVED** [review]
Looks good, some necessary minor changes to accomodate for an empty character grid and some new methods in presenter

**Review by patelhrid — APPROVED** [review]
Looks like it works

**Review by mhabibi9 — APPROVED** [review]

**Comment by JosephSun2003** [comment]
Note: just resolved some conflicts so the PR needs reapproval.

**Review by ethanhonest — APPROVED** [review]
Same review: Looks like the merge conflicts were resolved and the code remained the same, so here's my approval again

**Review by patelhrid — APPROVED** [review]

**Review by petesaiacct — APPROVED** [review]
Looks good.

**Review by JosephSun2003 — APPROVED** [review]
Resolved all conflicts so the program should be safe to merge. Code check will be required however.

**Review by ethanhonest — APPROVED** [review]
Looks good, reapproving after merge conflicts resolved

**Pull request merged**
