### PR TITLE
This Pull request has the Dictionary in it. It also has the basic frame of the Turn constructor

### PR DESCRIPTION
**Pull request by petesaiacct**
So the key here is: The dictionary is up and running, and can be called using its getter method. there should be clear comments in the file explaining this, but feel free to ask.

This Branch commit will lose all my commits to create it as I couldn't fix my last pull request to eliminate the Gradle files, so this branch was pulled fresh from the main, and just the Java, resources, and Test files were added with all else set to git ignore and not staged.

So hopefully no conflicts.

### CODE REVIEW

**Review by ethanhonest — DISMISSED** [review]
Looks good, and contains some core functionality that is necessary for everyone, so probably best to merge this in as soon as possible. Not a big deal, but it might be better to change the package name to core_entities.io or something that complies with naming conventions. Either way, I'll approve the request and that can be changed later.

**Review by patelhrid — APPROVED** [review]
All classes seem to contain the core functionalities we discussed, and the TurnBuilder and related nodes seem to be a good solution for running the turns of the game. Code looks well written enough for the rest of us to utilize it.

**Review by ethanhonest — DISMISSED** [review]
Looks good. It seems like you're adding new empty gradle files, but we still have some existing with the same name. Would that overwrite them?  If not, then it's no big deal (I know it's difficult to remove files from a pull request, I just don't want to mess up the gradle build)

I like the concept with the linked list denoting player turns. We'll discuss tomorrow about implementing the design with other team member's user stories, since I think there is a bit of overlap

I'll approve the request for now, so that people can get access to the dictionary object sooner. We should be able to reverse the changes if the it messes up the gradle files

**Review by mhabibi9 — COMMENTED** [review]
Good work writing the methods for all these classes. It does a good job representing the main functionality that the group wanted to represent. The code looks efficient for others who are interacting with the dictionary to work with.

**Review by JosephSun2003 — DISMISSED** [review]

**Review by ethanhonest — APPROVED** [review]
Looks good. One minor thing - I think we're going with the design of only having one controller and one presenter, so we shouldn't need the turn controller and turn presenter.

**Review by mhabibi9 — APPROVED** [review]

**Review by JosephSun2003 — APPROVED** [review]

**Pull request merged**
