### PR TITLE
Created core HumanPlayer Class

### PR DESCRIPTION
**Pull request by noonoo9**

### CODE REVIEW

**Review by ethanhonest — COMMENTED** [review]
Make sure you rebase your project to accomodate the new changes. It looks like you're still using the old package system, because LetterRack is no longer in that package.

**Comment by JosephSun2003** [comment]
BTW, fixed the merge conflicts so you don't need to update the branch and make another request.

**Review by petesaiacct — APPROVED** [review]
Looks good, with no issues.

**Review by ethanhonest — APPROVED** [review]
Code looks good thus far. We can discuss on Monday about potentially converting Player to an interface for my user story to allow for Factory, though. Also, you might want to move the files into an appropriately named package (i.e. core_entities.player for example)

**Review by minaccchiang — APPROVED** [review]
It looks fine.

**Pull request merged**
