### PR TITLE
Place word refill user story fixes

### PR DESCRIPTION
**Pull request by patelhrid**
Major code cleanup and changes and fixes to interactor and related code. Mainly made changes to work with View, ViewModel, and Presenter. Tests created as well, with possibility for more tests.

### CODE REVIEW

**Review by minaccchiang — DISMISSED** [review]

**Review by ethanhonest — COMMENTED** [review]
Same change as mina, please put the request model as a parameter to the method in your use case. Since I need to create these interactors in main, I can't know what word is being placed before the user places it, so I can't create the request model.

**Review by JosephSun2003 — DISMISSED** [review]
Things mostly look good and I didn't find any code smells on my end.

**Review by minaccchiang — DISMISSED** [review]

**Review by JosephSun2003 — APPROVED** [review]
Things mostly look good, and I didn't find any code smells on my end.

**Review by minaccchiang — APPROVED** [review]

**Comment by petesaiacct** [comment]
It looks functional, I would say that we might want to check code smells later for long data. But approved :)

**Review by petesaiacct — APPROVED** [review]
Will need to be refactored for code smells, but first things first, it looks functional and doesn't have any glaring issues that I see.

**Pull request merged**
