### PR TITLE
10 starting up application ethans user story

### PR DESCRIPTION
**Pull request by ethanhonest**
- Provides the framework for my use case
- Added method signature to Presenter Class which should implement my OutputBoundary
- Created csv file which contains the default Board data 

TO DO:
- Add gateway to my use case to accomodate input of csv (Currently no multipliers)
- Add testing to use case

### CODE REVIEW

**Comment by ethanhonest** [comment]
I should note - This use case implementation does not make use of factories for the rest of the entities. This was something we discussed in meeting today, and I am going to implement the use case without them for now so that we can have a working model sooner rather than later, and with time permitting, I will go back and add all the necessary factories to eliminate the direct dependencies.

**Review by JosephSun2003 — APPROVED** [review]
Everything seems to work but don't know how the other pull requests will handle this one.

**Review by minaccchiang — APPROVED** [review]
I did not see any specific issue.

**Review by mhabibi9 — APPROVED** [review]
Nice

**Review by djesurumc — APPROVED** [review]
Looks good. Would it be possible, however, to move your individual use case package into the general use_case package

**Pull request merged**
