### PR TITLE
73 updating exchanging letter use case

### PR DESCRIPTION
**Pull request by JosephSun2003**
Following Changes:
- Minor importing optimizations
- removed placeholder Code
- Added an output Boundary interface for my user story (ExchangeLetters).

### CODE REVIEW

**Review by ethanhonest — APPROVED** [review]
Looks good for the most part, minor change required in the parameter for update view model method but that can be added at a later date.

**Review by patelhrid — APPROVED** [review]
No obvious code smells. Looks good.

**Review by mhabibi9 — DISMISSED** [review]

**Review by ethanhonest — APPROVED** [review]
Looks like the merge conflicts were resolved and the code remained the same, so here's my approval again

**Review by patelhrid — APPROVED** [review]

**Comment by petesaiacct** [comment]
Got it. Good.

**Review by petesaiacct — APPROVED** [review]
Approved

**Pull request merged**
