### PR TITLE
Inbetween for merge

### PR DESCRIPTION
**Pull request by petesaiacct**
fixed tests improved search arrays by combining all combinations of letters greater than two characters into an assembled list. Added full comments for methods and functions. All tests passed in intellij for Gateway and Dictionary.

### CODE REVIEW

**Comment by petesaiacct** [comment]
Note, i had to remove some of Ethans changes, but he can re-add them after this Merge.

**Review by ethanhonest — APPROVED** [review]
Looks good to me, it looks like you made dictionary not serializable however, which is needed for saving the game

**Review by JosephSun2003 — APPROVED** [review]
Changes look good and homefully solve so testing problems.

**Review by JosephSun2003 — CHANGES_REQUESTED** [review]
GameState and Main.java are having issues since you've update dictionary. May you please fix them before merging? (Details should be under the 'Checks' tab at the top)

**Comment by ethanhonest** [comment]
The issues with game state are probably just due to the changes in method signature to dictionary, shouldn't be a problem. And main is a work in progress. I would approve these changes so I can use them to make sure everything still works.

**Review by JosephSun2003 — APPROVED** [review]
Approved for now.

**Review by patelhrid — APPROVED** [review]
Looks good to me, no obvious code smells.

**Review by mhabibi9 — APPROVED** [review]

**Pull request merged**
