### PR TITLE
Pete branch

### PR DESCRIPTION
**Pull request by petesaiacct**
This request is to put the Dictionary Class into the Main, as it is needed for other USE Case scenarios.

NOTE: The tests are not currently working. However the API of the getter will remain the same when the tests have been sorted. Thus it is more important tat this current point to get the code into Main, to enable other coders. And the completion of the tests and streamlining should not impact others.

### CODE REVIEW

**Review by minaccchiang — COMMENTED** [review]
The generate word method might need to go through the long dictionary, I'm wondering if it is possible for you to have a getter method for it?

**Review by patelhrid — APPROVED** [review]
Doesn't seem like there are any code smells that stand out. All code seems to be in the correct naming conventions, and is written fairly cleanly given that the code is in progress. Code looks like it works as intended.

**Comment by ethanhonest** [comment]
I noticed that a lot of files not directly modified were submitted in this request (i.e. gradle files, etc). Were any of these files modified? If not, would it be possible to submit the pull request without them? If so, is it possible to comment on why they were changed?

**Comment by ethanhonest** [comment]
Additionally, for turn constructor, why is verify location before getting and verifying the word? I think that the validity of the position would depend on the word (i.e. checking if the word intersects another word at the proper position)

**Review by JosephSun2003 — CHANGES_REQUESTED** [review]
One of the package names need changing. Otherwise, Code appears good.

**Pull request closed without merging**
